export type RouteMode = 'public' | 'private';
export type RouteSet = RouteMode | 'invalid';
export type RouteConfidence = 'explicit' | 'composed';

export type ExpectedValueType =
   | 'array'
   | 'boolean'
   | 'number'
   | 'object'
   | 'string';

export interface RouteExpectation {
   requiredPaths?: readonly string[];
   typedPaths?: Readonly<Record<string, ExpectedValueType>>;
   nonEmptyArrays?: readonly string[];
   samplePaths?: readonly string[];
}

export interface RouteDefinition {
   id: string;
   label: string;
   mode: RouteMode;
   confidence: RouteConfidence;
   pathTemplate: string;
   description?: string;
   expectations?: RouteExpectation;
}

function defineRoute(
   id: string,
   label: string,
   mode: RouteMode,
   confidence: RouteConfidence,
   pathTemplate: string,
   description: string,
   expectations?: RouteExpectation,
): RouteDefinition {
   return {
      id,
      label,
      mode,
      confidence,
      pathTemplate,
      description,
      expectations,
   };
}

const publicRoutes: RouteDefinition[] = [
   defineRoute(
      'public-game-by-id',
      'Game metadata by numeric key',
      'public',
      'explicit',
      '/game/{{PUBLIC_GAME_KEY}}',
      'Documented game root resource.',
      {
         requiredPaths: ['game.gameKey', 'game.code', 'game.season'],
         typedPaths: {
            'game.gameKey': 'string',
            'game.season': 'number',
         },
         samplePaths: ['game.name', 'game.code', 'game.season'],
      },
   ),
   defineRoute(
      'public-game-by-code',
      'Game metadata by game code',
      'public',
      'explicit',
      '/game/{{PUBLIC_GAME_CODE}}',
      'Documented game root resource using sport code.',
      {
         requiredPaths: ['game.gameKey', 'game.code', 'game.season'],
         typedPaths: {
            'game.gameKey': 'string',
            'game.season': 'number',
         },
         samplePaths: ['game.name', 'game.code', 'game.season'],
      },
   ),
   defineRoute(
      'public-game-leagues',
      'Game leagues collection',
      'public',
      'explicit',
      '/game/{{PUBLIC_GAME_CODE}}/leagues',
      'Safe explicit chain from the allowed chain matrix.',
   ),
   defineRoute(
      'public-game-leagues-by-key',
      'Game leagues collection scoped by league key',
      'public',
      'composed',
      '/game/{{PUBLIC_GAME_CODE}}/leagues;league_keys={{PUBLIC_LEAGUE_KEY}}',
      'Research-derived adjustment for game.leagues that succeeds with an explicit league key.',
   ),
   defineRoute(
      'public-game-players',
      'Game players collection',
      'public',
      'explicit',
      '/game/{{PUBLIC_GAME_CODE}}/players;search={{PUBLIC_PLAYER_SEARCH}};count={{COUNT_SMALL}}',
      'Documented game players search path.',
   ),
   defineRoute(
      'public-game-weeks',
      'Game weeks collection',
      'public',
      'explicit',
      '/game/{{PUBLIC_GAME_CODE}}/game_weeks',
      'Documented game week structure path.',
   ),
   defineRoute(
      'public-game-out',
      'Game out expansion',
      'public',
      'explicit',
      '/game/{{PUBLIC_GAME_CODE}};out=players,game_weeks',
      'Documented use of out on game root.',
   ),
   defineRoute(
      'public-games-available',
      'Available games collection',
      'public',
      'explicit',
      '/games;is_available=1',
      'Documented games collection filtered by availability.',
   ),
   defineRoute(
      'public-games-metadata',
      'Available games metadata collection',
      'public',
      'explicit',
      '/games;is_available=1/metadata',
      'Documented explicit metadata sub-resource on the games collection.',
   ),
   defineRoute(
      'public-games-by-code-season',
      'Games collection by code and season',
      'public',
      'explicit',
      '/games;game_codes={{PUBLIC_GAME_CODE}};seasons={{SEASON}}',
      'Documented games collection with game_codes and seasons.',
   ),
   defineRoute(
      'public-games-players',
      'Games players collection',
      'public',
      'explicit',
      '/games;game_keys={{GAME_KEY_FILTER}}/players;search={{PUBLIC_PLAYER_SEARCH}};count={{COUNT_SMALL}}',
      'Documented players collection under games.',
   ),
   defineRoute(
      'public-games-leagues',
      'Games leagues collection',
      'public',
      'explicit',
      '/games;game_codes={{PUBLIC_GAME_CODE}};seasons={{SEASON}}/leagues',
      'Documented leagues collection under games.',
   ),
   defineRoute(
      'public-games-leagues-by-key',
      'Games leagues collection scoped by league key',
      'public',
      'composed',
      '/games;game_codes={{PUBLIC_GAME_CODE}};seasons={{SEASON}}/leagues;league_keys={{PUBLIC_LEAGUE_KEY}}',
      'Research-derived adjustment for games.leagues that succeeds with an explicit league key.',
   ),
   defineRoute(
      'public-games-out',
      'Games out expansion',
      'public',
      'explicit',
      '/games;game_codes={{PUBLIC_GAME_CODE}};seasons={{SEASON}};out=leagues,players',
      'Documented use of out on the games collection.',
   ),
   defineRoute(
      'public-games-out-by-key',
      'Games out expansion by game key',
      'public',
      'explicit',
      '/games;game_keys={{GAME_KEY_FILTER}};out=leagues',
      'Documented games out expansion using explicit game_keys selection.',
   ),
   defineRoute(
      'public-games-out-by-key-players',
      'Games out expansion by game key with players',
      'public',
      'explicit',
      '/games;game_keys={{GAME_KEY_FILTER}};out=leagues,players',
      'Documented games out expansion using explicit game_keys selection with multiple sub-resources.',
   ),
   defineRoute(
      'public-game-leagues-teams',
      'Game leagues teams chain',
      'public',
      'composed',
      '/game/{{PUBLIC_GAME_CODE}}/leagues/teams',
      'Composed chain from game.leagues to teams.',
   ),
   defineRoute(
      'public-game-leagues-by-key-teams',
      'Game leagues teams chain scoped by league key',
      'public',
      'composed',
      '/game/{{PUBLIC_GAME_CODE}}/leagues;league_keys={{PUBLIC_LEAGUE_KEY}}/teams',
      'Research-derived adjustment for game.leagues.teams that succeeds with an explicit league key.',
   ),
   defineRoute(
      'public-game-leagues-players',
      'Game leagues players chain',
      'public',
      'composed',
      '/game/{{PUBLIC_GAME_CODE}}/leagues/players;search={{PUBLIC_PLAYER_SEARCH}};count={{COUNT_SMALL}}',
      'Composed chain from game.leagues to players.',
   ),
   defineRoute(
      'public-game-leagues-by-key-players',
      'Game leagues players chain scoped by league key',
      'public',
      'composed',
      '/game/{{PUBLIC_GAME_CODE}}/leagues;league_keys={{PUBLIC_LEAGUE_KEY}}/players;search={{PUBLIC_PLAYER_SEARCH}};count={{COUNT_SMALL}}',
      'Research-derived adjustment for game.leagues.players that succeeds with an explicit league key.',
   ),
   defineRoute(
      'public-game-leagues-transactions',
      'Game leagues transactions chain',
      'public',
      'composed',
      '/game/{{PUBLIC_GAME_CODE}}/leagues/transactions;count={{COUNT_SMALL}}',
      'Composed chain from game.leagues to transactions.',
   ),
   defineRoute(
      'public-game-leagues-by-key-transactions',
      'Game leagues transactions chain scoped by league key',
      'public',
      'composed',
      '/game/{{PUBLIC_GAME_CODE}}/leagues;league_keys={{PUBLIC_LEAGUE_KEY}}/transactions;count={{COUNT_SMALL}}',
      'Research-derived adjustment for game.leagues.transactions that succeeds with an explicit league key.',
   ),
   defineRoute(
      'public-games-leagues-teams',
      'Games leagues teams chain',
      'public',
      'composed',
      '/games;game_codes={{PUBLIC_GAME_CODE}};seasons={{SEASON}}/leagues/teams',
      'Composed chain from games.leagues to teams.',
   ),
   defineRoute(
      'public-games-leagues-by-key-teams',
      'Games leagues teams chain scoped by league key',
      'public',
      'composed',
      '/games;game_codes={{PUBLIC_GAME_CODE}};seasons={{SEASON}}/leagues;league_keys={{PUBLIC_LEAGUE_KEY}}/teams',
      'Research-derived adjustment for games.leagues.teams that succeeds with an explicit league key.',
   ),
   defineRoute(
      'public-games-leagues-players',
      'Games leagues players chain',
      'public',
      'composed',
      '/games;game_codes={{PUBLIC_GAME_CODE}}/leagues/players;search={{PUBLIC_PLAYER_SEARCH}};count={{COUNT_SMALL}}',
      'Composed chain from games.leagues to players.',
   ),
   defineRoute(
      'public-games-leagues-transactions',
      'Games leagues transactions chain',
      'public',
      'composed',
      '/games;game_codes={{PUBLIC_GAME_CODE}}/leagues/transactions;count={{COUNT_SMALL}}',
      'Composed chain from games.leagues to transactions.',
   ),
   defineRoute(
      'public-league-metadata',
      'Public league metadata',
      'public',
      'explicit',
      '/league/{{PUBLIC_LEAGUE_KEY}}',
      'Optional public league metadata probe.',
   ),
   defineRoute(
      'public-league-settings',
      'Public league settings',
      'public',
      'explicit',
      '/league/{{PUBLIC_LEAGUE_KEY}}/settings',
      'Optional public league settings probe.',
      {
         requiredPaths: ['league.leagueKey', 'league.settings'],
         typedPaths: {
            'league.settings': 'object',
         },
         samplePaths: [
            'league.name',
            'league.season',
            'league.settings.rosterPositions',
         ],
      },
   ),
   defineRoute(
      'public-league-standings',
      'Public league standings',
      'public',
      'explicit',
      '/league/{{PUBLIC_LEAGUE_KEY}}/standings',
      'Optional public league standings probe.',
   ),
   defineRoute(
      'public-league-scoreboard',
      'Public league scoreboard',
      'public',
      'explicit',
      '/league/{{PUBLIC_LEAGUE_KEY}}/scoreboard;week={{WEEK}}',
      'Optional public league scoreboard probe.',
   ),
   defineRoute(
      'public-league-teams',
      'Public league teams',
      'public',
      'explicit',
      '/league/{{PUBLIC_LEAGUE_KEY}}/teams',
      'Optional public league teams probe.',
   ),
   defineRoute(
      'public-league-players',
      'Public league players',
      'public',
      'explicit',
      '/league/{{PUBLIC_LEAGUE_KEY}}/players;search={{PUBLIC_PLAYER_SEARCH}};count={{COUNT_SMALL}}',
      'Optional public league-context players probe.',
   ),
   defineRoute(
      'public-league-transactions',
      'Public league transactions',
      'public',
      'explicit',
      '/league/{{PUBLIC_LEAGUE_KEY}}/transactions;count={{COUNT_SMALL}}',
      'Optional public league transactions probe.',
   ),
];

const privateRoutes: RouteDefinition[] = [
   defineRoute(
      'private-users-root',
      'Authenticated user root',
      'private',
      'explicit',
      '/users;use_login=1',
      'Minimal OAuth2 sanity check for user scope.',
      {
         samplePaths: ['guid', 'users.0.guid', 'users.guid'],
      },
   ),
   defineRoute(
      'private-users-games',
      'Authenticated user games',
      'private',
      'explicit',
      '/users;use_login=1/games',
      'Documented user discovery path for games.',
   ),
   defineRoute(
      'private-users-games-filtered',
      'Authenticated user games filtered',
      'private',
      'explicit',
      '/users;use_login=1/games;game_keys={{GAME_KEY_FILTER}}',
      'Documented user games filter path.',
   ),
   defineRoute(
      'private-users-games-leagues',
      'Authenticated user game leagues',
      'private',
      'explicit',
      '/users;use_login=1/games;game_keys={{GAME_KEY_FILTER}}/leagues',
      'Documented user discovery path for leagues by game.',
   ),
   defineRoute(
      'private-users-games-teams',
      'Authenticated user game teams',
      'private',
      'explicit',
      '/users;use_login=1/games;game_keys={{GAME_KEY_FILTER}}/teams',
      'Documented user discovery path for teams by game.',
   ),
   defineRoute(
      'private-users-games-out',
      'Authenticated user games out expansion',
      'private',
      'explicit',
      '/users;use_login=1/games;game_keys={{GAME_KEY_FILTER}};out=leagues,teams',
      'Documented user games out expansion.',
   ),
   defineRoute(
      'private-users-leagues',
      'Authenticated user leagues root',
      'private',
      'composed',
      '/users;use_login=1/leagues',
      'Composed users.leagues chain from allowed chain matrix.',
   ),
   defineRoute(
      'private-users-out-leagues',
      'Authenticated user leagues root via out expansion',
      'private',
      'composed',
      '/users;use_login=1;out=leagues',
      'Research-derived out expansion variant for users.leagues.',
   ),
   defineRoute(
      'private-users-teams',
      'Authenticated user teams root',
      'private',
      'composed',
      '/users;use_login=1/teams',
      'Composed users.teams chain from allowed chain matrix.',
   ),
   defineRoute(
      'private-users-games-leagues-teams',
      'Authenticated user game leagues teams',
      'private',
      'composed',
      '/users;use_login=1/games;game_keys={{GAME_KEY_FILTER}}/leagues/teams',
      'Composed users.games.leagues.teams chain.',
   ),
   defineRoute(
      'private-users-games-leagues-players',
      'Authenticated user game leagues players',
      'private',
      'composed',
      '/users;use_login=1/games;game_keys={{GAME_KEY_FILTER}}/leagues/players;search={{PRIVATE_PLAYER_SEARCH}};count={{COUNT_SMALL}}',
      'Composed users.games.leagues.players chain.',
   ),
   defineRoute(
      'private-users-games-leagues-settings',
      'Authenticated user game leagues settings',
      'private',
      'composed',
      '/users;use_login=1/games;game_keys={{GAME_KEY_FILTER}}/leagues/settings',
      'Composed users.games.leagues.settings chain.',
   ),
   defineRoute(
      'private-users-games-teams-roster',
      'Authenticated user game teams roster',
      'private',
      'composed',
      '/users;use_login=1/games;game_keys={{GAME_KEY_FILTER}}/teams/roster',
      'Composed users.games.teams.roster chain.',
   ),
   defineRoute(
      'private-league-metadata',
      'Private league metadata',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}',
      'Documented league metadata path.',
   ),
   defineRoute(
      'private-league-settings',
      'Private league settings',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/settings',
      'Documented league settings path.',
      {
         requiredPaths: ['league.leagueKey', 'league.settings'],
         typedPaths: {
            'league.settings': 'object',
         },
         samplePaths: [
            'league.name',
            'league.season',
            'league.settings.rosterPositions',
         ],
      },
   ),
   defineRoute(
      'private-league-standings',
      'Private league standings',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/standings',
      'Documented league standings path.',
   ),
   defineRoute(
      'private-league-scoreboard',
      'Private league scoreboard',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/scoreboard;week={{WEEK}}',
      'Documented league scoreboard path.',
   ),
   defineRoute(
      'private-league-teams',
      'Private league teams',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/teams',
      'Documented league teams path.',
   ),
   defineRoute(
      'private-league-players-status',
      'Private league available players',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/players;status=FA;position={{PRIVATE_PLAYER_POSITION}};count={{COUNT_SMALL}}',
      'Documented league players path with availability filters.',
   ),
   defineRoute(
      'private-league-players-search',
      'Private league player search',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/players;search={{PRIVATE_PLAYER_SEARCH}};count={{COUNT_SMALL}}',
      'Documented league players search path.',
   ),
   defineRoute(
      'private-league-players-sorted',
      'Private league players sorted view',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/players;status=FA;position={{PRIVATE_PLAYER_POSITION}};sort=PTS;sort_type=season;sort_season={{SEASON}};start=0;count={{COUNT_SMALL}}',
      'Documented league players path combining status, position, sorting, and pagination filters.',
   ),
   defineRoute(
      'private-league-transactions',
      'Private league transactions',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/transactions;count={{COUNT_SMALL}}',
      'Documented league transactions path.',
   ),
   defineRoute(
      'private-league-transactions-filtered',
      'Private league transactions filtered',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/transactions;type={{PRIVATE_TRANSACTION_TYPE}};team_key={{PRIVATE_TEAM_KEY}};count={{COUNT_SMALL}}',
      'Documented league transactions path with team and type filters.',
   ),
   defineRoute(
      'private-league-transactions-by-keys',
      'Private league transactions by keys',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/transactions;transaction_keys={{PRIVATE_TRANSACTION_KEYS}}',
      'Documented keyed transaction collection under league transactions.',
   ),
   defineRoute(
      'private-league-transactions-out',
      'Private league transactions out expansion',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/transactions;transaction_keys={{PRIVATE_TRANSACTION_KEYS}};out=players',
      'Documented use of out on a keyed transaction collection.',
   ),
   defineRoute(
      'private-league-transactions-types',
      'Private league transactions by multiple types',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/transactions;types=add,trade;count={{COUNT_SMALL}}',
      'Documented league transactions path using the multi-type filter.',
   ),
   defineRoute(
      'private-league-transactions-players',
      'Private league transaction players',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/transactions;transaction_keys={{PRIVATE_TRANSACTION_KEYS}}/players',
      'Safe explicit chain for transaction players.',
   ),
   defineRoute(
      'private-league-out',
      'Private league out expansion',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}};out=settings,standings,scoreboard',
      'Documented use of out on league root.',
   ),
   defineRoute(
      'private-leagues-root',
      'Private leagues collection',
      'private',
      'explicit',
      '/leagues;league_keys={{PRIVATE_LEAGUE_KEYS}}',
      'Documented leagues collection by key.',
   ),
   defineRoute(
      'private-leagues-settings',
      'Private leagues settings collection',
      'private',
      'explicit',
      '/leagues;league_keys={{PRIVATE_LEAGUE_KEYS}}/settings',
      'Documented leagues.settings collection path.',
   ),
   defineRoute(
      'private-leagues-standings',
      'Private leagues standings collection',
      'private',
      'explicit',
      '/leagues;league_keys={{PRIVATE_LEAGUE_KEYS}}/standings',
      'Documented leagues.standings collection path.',
   ),
   defineRoute(
      'private-leagues-teams',
      'Private leagues teams collection',
      'private',
      'explicit',
      '/leagues;league_keys={{PRIVATE_LEAGUE_KEYS}}/teams',
      'Documented leagues.teams collection path.',
   ),
   defineRoute(
      'private-leagues-players',
      'Private leagues players collection',
      'private',
      'explicit',
      '/leagues;league_keys={{PRIVATE_LEAGUE_KEYS}}/players;search={{PRIVATE_PLAYER_SEARCH}};count={{COUNT_SMALL}}',
      'Documented leagues.players collection path.',
   ),
   defineRoute(
      'private-leagues-transactions',
      'Private leagues transactions collection',
      'private',
      'explicit',
      '/leagues;league_keys={{PRIVATE_LEAGUE_KEYS}}/transactions;count={{COUNT_SMALL}}',
      'Documented leagues.transactions collection path.',
   ),
   defineRoute(
      'private-leagues-scoreboard',
      'Private leagues scoreboard collection',
      'private',
      'explicit',
      '/leagues;league_keys={{PRIVATE_LEAGUE_KEYS}}/scoreboard;week={{WEEK}}',
      'Documented leagues.scoreboard collection path.',
   ),
   defineRoute(
      'private-leagues-out',
      'Private leagues out expansion',
      'private',
      'explicit',
      '/leagues;league_keys={{PRIVATE_LEAGUE_KEYS}};out=settings,standings',
      'Documented use of out on the leagues collection.',
   ),
   defineRoute(
      'private-leagues-teams-roster',
      'Private leagues teams roster chain',
      'private',
      'composed',
      '/leagues;league_keys={{PRIVATE_LEAGUE_KEYS}}/teams/roster;week={{WEEK}}',
      'Composed leagues.teams.roster chain.',
   ),
   defineRoute(
      'private-leagues-teams-roster-players',
      'Private leagues teams roster players chain',
      'private',
      'composed',
      '/leagues;league_keys={{PRIVATE_LEAGUE_KEYS}}/teams/roster;week={{WEEK}}/players',
      'Composed leagues.teams.roster.players chain.',
   ),
   defineRoute(
      'private-team-metadata',
      'Private team metadata',
      'private',
      'explicit',
      '/team/{{PRIVATE_TEAM_KEY}}',
      'Documented team metadata path.',
   ),
   defineRoute(
      'private-team-roster',
      'Private team roster',
      'private',
      'explicit',
      '/team/{{PRIVATE_TEAM_KEY}}/roster',
      'Documented team roster path.',
      {
         requiredPaths: [
            'team.teamKey',
            'team.roster',
            'team.roster.players',
         ],
         typedPaths: {
            'team.roster': 'object',
            'team.roster.players': 'array',
         },
         samplePaths: [
            'team.name',
            'team.roster.date',
            'team.roster.players.0.name.full',
         ],
      },
   ),
   defineRoute(
      'private-team-roster-players-week',
      'Private team roster players by week',
      'private',
      'explicit',
      '/team/{{PRIVATE_TEAM_KEY}}/roster;week={{WEEK}}/players',
      'Documented team roster players week path.',
   ),
   defineRoute(
      'private-team-roster-players-date',
      'Private team roster players by date',
      'private',
      'explicit',
      '/team/{{PRIVATE_TEAM_KEY}}/roster;date={{DATE}}/players',
      'Documented team roster players date path.',
   ),
   defineRoute(
      'private-team-matchups',
      'Private team matchups',
      'private',
      'explicit',
      '/team/{{PRIVATE_TEAM_KEY}}/matchups;weeks={{WEEK}},{{ALT_WEEK}}',
      'Documented team matchups path.',
   ),
   defineRoute(
      'private-team-stats',
      'Private team stats',
      'private',
      'explicit',
      '/team/{{PRIVATE_TEAM_KEY}}/stats;type=season',
      'Documented team stats path.',
   ),
   defineRoute(
      'private-team-stats-date',
      'Private team stats by date',
      'private',
      'explicit',
      '/team/{{PRIVATE_TEAM_KEY}};out=standings,stats;type=date;date={{DATE}}',
      'Documented team stats path with date coverage.',
   ),
   defineRoute(
      'private-team-out',
      'Private team out expansion',
      'private',
      'explicit',
      '/team/{{PRIVATE_TEAM_KEY}};out=roster,stats,matchups',
      'Documented use of out on team root.',
   ),
   defineRoute(
      'private-teams-root',
      'Private teams collection',
      'private',
      'explicit',
      '/teams;team_keys={{PRIVATE_TEAM_KEYS}}',
      'Documented teams collection by key.',
   ),
   defineRoute(
      'private-teams-roster',
      'Private teams roster collection',
      'private',
      'explicit',
      '/teams;team_keys={{PRIVATE_TEAM_KEYS}}/roster;week={{WEEK}}',
      'Documented teams.roster collection path.',
   ),
   defineRoute(
      'private-teams-roster-players',
      'Private teams roster players collection',
      'private',
      'explicit',
      '/teams;team_keys={{PRIVATE_TEAM_KEYS}}/roster;week={{WEEK}}/players',
      'Documented teams.roster.players collection path.',
   ),
   defineRoute(
      'private-teams-matchups',
      'Private teams matchups collection',
      'private',
      'explicit',
      '/teams;team_keys={{PRIVATE_TEAM_KEYS}}/matchups;weeks={{WEEK}},{{ALT_WEEK}}',
      'Documented teams.matchups collection path.',
   ),
   defineRoute(
      'private-teams-stats',
      'Private teams stats collection',
      'private',
      'explicit',
      '/teams;team_keys={{PRIVATE_TEAM_KEYS}}/stats;type=season',
      'Documented teams.stats collection path.',
   ),
   defineRoute(
      'private-teams-out',
      'Private teams out expansion',
      'private',
      'explicit',
      '/teams;team_keys={{PRIVATE_TEAM_KEYS}};out=roster,stats',
      'Documented use of out on the teams collection.',
   ),
   defineRoute(
      'private-teams-roster-date',
      'Private teams roster players by date',
      'private',
      'explicit',
      '/teams;team_keys={{PRIVATE_TEAM_KEYS}}/roster;date={{DATE}}/players',
      'Documented teams.roster.players collection path with date coverage.',
   ),
   defineRoute(
      'private-teams-stats-date',
      'Private teams stats collection by date',
      'private',
      'explicit',
      '/teams;team_keys={{PRIVATE_TEAM_KEYS}}/stats;type=date;date={{DATE}}',
      'Documented teams.stats collection path with date coverage.',
   ),
   defineRoute(
      'private-player-metadata',
      'Private player metadata',
      'private',
      'explicit',
      '/player/{{PRIVATE_PLAYER_KEY}}',
      'Documented player metadata path.',
   ),
   defineRoute(
      'private-player-stats',
      'Private player stats',
      'private',
      'explicit',
      '/player/{{PRIVATE_PLAYER_KEY}}/stats;type=season',
      'Documented player stats path.',
   ),
   defineRoute(
      'private-player-ownership',
      'Private player ownership',
      'private',
      'explicit',
      '/player/{{PRIVATE_PLAYER_KEY}}/ownership',
      'Documented player ownership path.',
   ),
   defineRoute(
      'private-player-percent-owned',
      'Private player percent owned',
      'private',
      'explicit',
      '/player/{{PRIVATE_PLAYER_KEY}}/percent_owned',
      'Documented player percent owned path.',
   ),
   defineRoute(
      'private-player-out',
      'Private player out expansion',
      'private',
      'explicit',
      '/player/{{PRIVATE_PLAYER_KEY}};out=stats,ownership',
      'Documented use of out on player root.',
   ),
   defineRoute(
      'private-players-root',
      'Private players collection',
      'private',
      'explicit',
      '/players;player_keys={{PRIVATE_PLAYER_KEYS}}',
      'Documented players collection by key.',
   ),
   defineRoute(
      'private-players-stats',
      'Private players stats collection',
      'private',
      'explicit',
      '/players;player_keys={{PRIVATE_PLAYER_KEYS}}/stats',
      'Safe explicit players.stats chain.',
   ),
   defineRoute(
      'private-players-ownership',
      'Private players ownership collection',
      'private',
      'composed',
      '/players;player_keys={{PRIVATE_PLAYER_KEYS}}/ownership',
      'Composed players.ownership chain.',
   ),
   defineRoute(
      'private-players-percent-owned',
      'Private players percent owned collection',
      'private',
      'composed',
      '/players;player_keys={{PRIVATE_PLAYER_KEYS}}/percent_owned',
      'Composed players.percent_owned chain.',
   ),
   defineRoute(
      'private-transaction-metadata',
      'Private transaction metadata',
      'private',
      'explicit',
      '/transaction/{{PRIVATE_TRANSACTION_KEY}}',
      'Documented transaction metadata path.',
   ),
   defineRoute(
      'private-transaction-players',
      'Private transaction players chain',
      'private',
      'explicit',
      '/transaction/{{PRIVATE_TRANSACTION_KEY}}/players',
      'Explicit transaction.players chain from the allowed chain matrix.',
   ),
   defineRoute(
      'private-league-teams-roster',
      'Private league teams roster chain',
      'private',
      'composed',
      '/league/{{PRIVATE_LEAGUE_KEY}}/teams;team_keys={{PRIVATE_TEAM_KEYS}}/roster;week={{WEEK}}',
      'Composed league.teams.roster chain.',
   ),
   defineRoute(
      'private-league-teams-roster-players',
      'Private league teams roster players chain',
      'private',
      'composed',
      '/league/{{PRIVATE_LEAGUE_KEY}}/teams;team_keys={{PRIVATE_TEAM_KEYS}}/roster;week={{WEEK}}/players',
      'Composed league.teams.roster.players chain.',
   ),
   defineRoute(
      'private-league-players-stats',
      'Private league players stats chain',
      'private',
      'explicit',
      '/league/{{PRIVATE_LEAGUE_KEY}}/players;player_keys={{PRIVATE_PLAYER_KEYS}}/stats',
      'Explicit league.players.stats chain.',
   ),
   defineRoute(
      'private-league-players-ownership',
      'Private league players ownership chain',
      'private',
      'composed',
      '/league/{{PRIVATE_LEAGUE_KEY}}/players;player_keys={{PRIVATE_PLAYER_KEYS}}/ownership',
      'Composed league.players.ownership chain.',
   ),
   defineRoute(
      'private-league-players-percent-owned',
      'Private league players percent owned chain',
      'private',
      'composed',
      '/league/{{PRIVATE_LEAGUE_KEY}}/players;player_keys={{PRIVATE_PLAYER_KEYS}}/percent_owned',
      'Composed league.players.percent_owned chain.',
   ),
];

const INVALID_ROUTE_IDS = new Set<string>([
   'public-game-leagues',
   'public-games-leagues',
   'public-games-out',
   'public-games-out-by-key',
   'public-games-out-by-key-players',
   'public-game-leagues-teams',
   'public-game-leagues-players',
   'public-game-leagues-transactions',
   'public-games-leagues-teams',
   'public-games-leagues-players',
   'public-games-leagues-transactions',
   'private-users-leagues',
   'private-users-out-leagues',
   'private-league-players-sorted',
   'private-league-transactions-by-keys',
   'private-league-transactions-out',
   'private-league-transactions-players',
   'private-transaction-metadata',
   'private-transaction-players',
]);

function isInvalidRoute(route: RouteDefinition): boolean {
   return INVALID_ROUTE_IDS.has(route.id);
}

// Docs-derived testing surface from PATH_REFERENCE_TABLE, PATH_DECISION_TREE,
// PATH_CHEAT_SHEET, and ALLOWED_CHAIN_MATRIX, split into default supported
// routes plus known failing probes kept for explicit reproduction runs.
export const STATIC_ROUTE_SETS: Record<RouteSet, RouteDefinition[]> = {
   public: publicRoutes.filter((route) => !isInvalidRoute(route)),
   private: privateRoutes.filter((route) => !isInvalidRoute(route)),
   invalid: [
      ...publicRoutes.filter((route) => isInvalidRoute(route)),
      ...privateRoutes.filter((route) => isInvalidRoute(route)),
   ],
};
