import type { StageSpec } from './shared.js';
import {
   gameOutValues,
   leagueOutValues,
   leagueRootParams,
   playerCollectionParams,
   playerOutValues,
   scoreboardParams,
   statsCoverageParams,
   teamOutValues,
   teamRootParams,
   transactionCollectionParams,
   transactionOutValues,
} from './shared.js';

export const gameStages = {
   'game.leagues': {
      params: leagueRootParams,
      next: {
         settings: 'game.leagues.settings',
         standings: 'game.leagues.standings',
         scoreboard: 'game.leagues.scoreboard',
         teams: 'game.leagues.teams',
         players: 'game.leagues.players',
         transactions: 'game.leagues.transactions',
         drafts: 'game.leagues.drafts',
      },
      outValues: leagueOutValues,
      confidence: 'composed',
   },
   'game.players': {
      params: playerCollectionParams,
      next: {
         stats: 'game.players.stats',
         ownership: 'game.players.ownership',
         percentOwned: 'game.players.percent_owned',
         draftAnalysis: 'game.players.draft_analysis',
      },
      outValues: playerOutValues,
      confidence: 'explicit',
   },
   'game.stat_categories': { confidence: 'experimental' },
   'game.position_types': { confidence: 'experimental' },
   'game.game_weeks': { confidence: 'explicit' },
   'games.leagues': {
      params: leagueRootParams,
      next: {
         settings: 'games.leagues.settings',
         standings: 'games.leagues.standings',
         scoreboard: 'games.leagues.scoreboard',
         teams: 'games.leagues.teams',
         players: 'games.leagues.players',
         transactions: 'games.leagues.transactions',
         drafts: 'games.leagues.drafts',
      },
      outValues: leagueOutValues,
      confidence: 'composed',
   },
   'games.players': {
      params: playerCollectionParams,
      next: {
         stats: 'games.players.stats',
         ownership: 'games.players.ownership',
         percentOwned: 'games.players.percent_owned',
         draftAnalysis: 'games.players.draft_analysis',
      },
      outValues: playerOutValues,
      confidence: 'composed',
   },
   'games.game_weeks': { confidence: 'composed' },
   'game.leagues.settings': { confidence: 'composed' },
   'game.leagues.standings': { confidence: 'composed' },
   'game.leagues.scoreboard': {
      params: scoreboardParams,
      confidence: 'composed',
   },
   'game.leagues.teams': {
      params: teamRootParams,
      next: {
         roster: 'game.leagues.teams.roster',
         matchups: 'game.leagues.teams.matchups',
         stats: 'game.leagues.teams.stats',
         standings: 'game.leagues.teams.standings',
      },
      outValues: teamOutValues,
      confidence: 'composed',
   },
   'game.leagues.players': {
      params: playerCollectionParams,
      confidence: 'composed',
   },
   'game.leagues.transactions': {
      params: transactionCollectionParams,
      outValues: transactionOutValues,
      confidence: 'composed',
   },
   'game.leagues.drafts': { confidence: 'experimental' },
   'games.leagues.settings': { confidence: 'composed' },
   'games.leagues.standings': { confidence: 'composed' },
   'games.leagues.scoreboard': {
      params: scoreboardParams,
      confidence: 'composed',
   },
   'games.leagues.teams': {
      params: teamRootParams,
      next: {
         roster: 'games.leagues.teams.roster',
         matchups: 'games.leagues.teams.matchups',
         stats: 'games.leagues.teams.stats',
         standings: 'games.leagues.teams.standings',
      },
      outValues: teamOutValues,
      confidence: 'composed',
   },
   'games.leagues.players': {
      params: playerCollectionParams,
      confidence: 'composed',
   },
   'games.leagues.transactions': {
      params: transactionCollectionParams,
      outValues: transactionOutValues,
      confidence: 'composed',
   },
   'games.leagues.drafts': { confidence: 'experimental' },
   'game.players.stats': {
      params: statsCoverageParams,
      confidence: 'composed',
   },
   'game.players.ownership': { confidence: 'composed' },
   'game.players.percent_owned': { confidence: 'composed' },
   'game.players.draft_analysis': { confidence: 'experimental' },
   'games.players.stats': {
      params: statsCoverageParams,
      confidence: 'composed',
   },
   'games.players.ownership': { confidence: 'composed' },
   'games.players.percent_owned': { confidence: 'composed' },
   'games.players.draft_analysis': { confidence: 'experimental' },
} as const satisfies Record<string, StageSpec>;
